const {Router} = require("express")
const authRoutes = require("./auth.routes")
const userRoutes = require("./user.routes")
const levelRoutes = require("./level.routes")
const tagRoutes = require("./tag.routes")
const articleRoutes = require("./article.routes")
const bookRoutes = require("./book.routes")
const courseRoutes = require("./course.routes")
const offRoutes = require("./off.routes")
const commentRoutes = require("./comment.routes")
const sessionRoutes = require("./session.routes")
const saleRoutes = require("./sale.routes")
const ticketRoutes = require("./ticket.routes")
const roleRoutes = require("./role.routes")
const consoleRoutes = require("./Console.routes")
const searchRoutes = require("./userSearch.routes")
const contactRoutes = require("./contact.routes")
const extraFileRoutes = require("./extrafile.routes")

const router = Router()

router.use("/auth" , authRoutes)
router.use("/user" , userRoutes)
router.use("/level" , levelRoutes)
router.use("/tag" , tagRoutes)
router.use("/article" , articleRoutes)
router.use("/book" , bookRoutes)
router.use("/course" , courseRoutes)
router.use("/off" , offRoutes)
router.use("/comment" , commentRoutes)
router.use("/session" , sessionRoutes)
router.use("/sale" , saleRoutes)
router.use("/ticket" , ticketRoutes)
router.use("/role" , roleRoutes)
router.use("/console" , consoleRoutes)
router.use("/search" , searchRoutes)
router.use("/contact" , contactRoutes)
router.use("/extra-file" , extraFileRoutes)

module.exports = router